_BASE_: "Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.yaml"
MODEL:
  META_ARCHITECTURE: "LabelingDetic"
  WEIGHTS: "weights/detic/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth"
  ROI_BOX_HEAD:
    ZEROSHOT_WEIGHT_PATH: 'Detic/datasets/metadata/oid_clip_a+cname.npy'
  ROI_HEADS:
    NUM_CLASSES: 500
DATASETS:
  TEST: ('imagenet_1k_train',)