_BASE_: ../mask2former/coco/instance-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_100ep.yaml
DATASETS:
  TRAIN: ("imagenet_1k_train",)
  TEST: ("part_imagenet_match_val","part_imagenet_evaluate_val",)
MODEL:
  SWIN:
    USE_CHECKPOINT: False 
  WEIGHTS: "weights/m2f/instance/swinL_i21k_q200_e100.pkl"
  META_ARCHITECTURE: "PartDistillationModel"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "PartDistillationTransformerDecoder"
INPUT:
  MIN_SIZE_TRAIN: (640,)
  MIN_SIZE_TEST: 640
  IMAGE_SIZE: 640
  MASK_FORMAT: "bitmask"
  SIZE_DIVISIBILITY: 16
TEST:
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 200
SOLVER:
  IMS_PER_BATCH: 32
WANDB:
  PROJECT: "PartDistillationTrain"